### ISSUE TITLE
undefined method `delete_if' for nil:NilClass

### ISSUE THREAD

**Issue by bwc** [edtsech/redmine_wiki_permissions#2]
After installing this plugin, if I click on the word search in the upper right corner to go to search I get a 500 error.  I am on redmine trunk at r3200

url: https://redmine.fishpond.co.nz/search/index/bgz

production.log:

Processing SearchController#index (for 60.234.173.23 at 2009-12-21 12:21:31) [GET]
  Parameters: {"action"=>"index", "id"=>"bgz", "controller"=>"search"}

NoMethodError (undefined method `delete_if' for nil:NilClass):
  passenger (2.2.4) lib/phusion_passenger/rack/request_handler.rb:91:in`process_request'
  passenger (2.2.4) lib/phusion_passenger/abstract_request_handler.rb:206:in `main_loop'
  passenger (2.2.4) lib/phusion_passenger/railz/application_spawner.rb:376:in`start_request_handler'
  passenger (2.2.4) lib/phusion_passenger/railz/application_spawner.rb:334:in `handle_spawn_application'
  passenger (2.2.4) lib/phusion_passenger/utils.rb:182:in`safe_fork'
  passenger (2.2.4) lib/phusion_passenger/railz/application_spawner.rb:332:in `handle_spawn_application'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:351:in`**send**'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:351:in `main_loop'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:195:in`start_synchronously'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:162:in `start'
  passenger (2.2.4) lib/phusion_passenger/railz/application_spawner.rb:213:in`start'
  passenger (2.2.4) lib/phusion_passenger/spawn_manager.rb:261:in `spawn_rails_application'
  passenger (2.2.4) lib/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  passenger (2.2.4) lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  passenger (2.2.4) lib/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  passenger (2.2.4) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (2.2.4) lib/phusion_passenger/spawn_manager.rb:254:in`spawn_rails_application'
  passenger (2.2.4) lib/phusion_passenger/spawn_manager.rb:153:in `spawn_application'
  passenger (2.2.4) lib/phusion_passenger/spawn_manager.rb:286:in`handle_spawn_application'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:351:in `__send__'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:351:in`main_loop'
  passenger (2.2.4) lib/phusion_passenger/abstract_server.rb:195:in `start_synchronously'

Rendering /mnt/redminevol/redmine_new/public/500.html (500 Internal Server Error)

When I comment out the delete_if in redmine_wiki_permissions/lib/wiki_permissions.rb and restart, the page renders ok.

**Comment by bwc** [comment]
Changing those lines to the following seems to fix it:

```
     if defined? results then
    @results.delete_if do |result|
          result.class == WikiPage and
            not User.current.can_view? result
        end
      end
```
